algoritmo "CalculoPerimetroTriangulo"

var

   lado1, lado2, lado3, perimetro: real

inicio

   escreva("Digite o tamanho do primeiro lado do triângulo: ")
   leia(lado1)
   escreva("Digite o tamanho do segundo lado do triângulo: ")
   leia(lado2)
   escreva("Digite o tamanho do terceiro lado do triângulo: ")
   leia(lado3)
   perimetro <- lado1 + lado2 + lado3
   escreval("O perímetro do triângulo é: ", perimetro)
   
fimalgoritmo